In [5]:
import numpy as np
    
a = np.array([[1,2,3],[4,5,6],[7,8,9]])    
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("First\n",a)
print("Second\n",b)
        
dot_product = np.dot(a,b)    
print("Dot product\n",dot_product)

First
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Second
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dot product
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [6]:
transpose_a = np.transpose(a)
transpose_b = np.transpose(b)

print("First\n",a)
print("Second\n",b)
print(f"---------------------------")
print(f"Transpose of A : \n{transpose_a}")
print(f"Transpose of B : \n{transpose_b}")

First
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Second
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
---------------------------
Transpose of A : 
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Transpose of B : 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [7]:
print(f"Trace of A : {np.trace(a)}")
print(f"Trace of B: {np.trace(b)}")

Trace of A : 15
Trace of B: 15


In [8]:
print(f"Rank of A : {np.linalg.matrix_rank(a)}")
print(f"Rank of B: {np.linalg.matrix_rank(b)}")

Rank of A : 2
Rank of B: 2


In [9]:
x = np.array([[7,7,3],[4,5,6],[7,8,9]])
y = np.array([[5,8,1],[7,9,3],[5,3,2]])

det_a = int(np.linalg.det(x))
det_b = int(np.linalg.det(y))
print(f"Determinant of A: {det_a}")
print(f"Determinant of B: {det_b}")

Determinant of A: 12
Determinant of B: 28


In [10]:
print("First\n",x)
print("Second\n",y)

inv_a = np.linalg.inv(x)
inv_b = np.linalg.inv(y)

print(f"Inverse of X:\n{inv_a}")
print(f"Inverse of Y:\n{inv_b}")

First
 [[7 7 3]
 [4 5 6]
 [7 8 9]]
Second
 [[5 8 1]
 [7 9 3]
 [5 3 2]]
Inverse of X:
[[-0.25       -3.25        2.25      ]
 [ 0.5         3.5        -2.5       ]
 [-0.25       -0.58333333  0.58333333]]
Inverse of Y:
[[ 0.31034483 -0.44827586  0.51724138]
 [ 0.03448276  0.17241379 -0.27586207]
 [-0.82758621  0.86206897 -0.37931034]]


In [11]:
m = np.array([[1, 2],[2, 3]])

value,vector = np.linalg.eig(m)
print(f"Eigen value of M: {value}")
print(f"Eigen vector of  M {vector}")

Eigen value of M: [-0.23606798  4.23606798]
Eigen vector of  M [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]
