In [3]:
import numpy as np

In [4]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([4,3,5,6,4])

In [5]:
np.greater(arr1,arr2)

array([False, False, False, False,  True])

In [8]:
np.greater_equal(arr1,arr2)

array([False, False, False, False,  True])

In [9]:
np.less(arr1,arr2)

array([ True,  True,  True,  True, False])

In [10]:
np.less_equal(arr1,arr2)

array([ True,  True,  True,  True, False])

In [11]:
arr = np.arange(30,71,2)
print(arr)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [12]:
arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
arr = np.array([[1,2,3],[3,4,5]])
arr.ndim

2

In [14]:
vector = np.arange(21)
vector[9:16] *= -1
print(vector)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [15]:
arr = np.zeros((5,5))
np.fill_diagonal(arr, [1,2,3,4,5])
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


In [19]:
arr = np.array([[1,2,3,4,5],[4,5,6,7,8]])

In [20]:
print(np.sum(arr))

45


In [27]:
print("Sum Row : ",np.sum(arr,axis=1))

Sum Row :  [15 30]


In [46]:
print("Sum Column : ",np.sum(arr,axis=0))

Sum Column :  [ 5  7  9 11 13]


In [47]:
data = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [48]:
file_name = "file.txt"
np.savetxt(file_name,data)

In [51]:
loaded_data = np.loadtxt(file_name)
print(loaded_data)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [52]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])

True

In [53]:
np.array_equal(arr1,arr2)

True

In [55]:
arr1 == arr2

array([ True,  True,  True,  True,  True])

In [68]:
arr1 = np.random.randint(1,50,(4,4))
print(arr1)

[[23 31 33 43]
 [18 44 43 27]
 [21  9 37 48]
 [43  4 17 46]]


In [ ]:
arr1[[0,-1],:]=arr1[[-1,0],:]
new_arr = arr1[[-1,1,2,0]]
print(new_arr)

: 

In [71]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([2,3,4,5,6])
np.multiply(arr1,arr2)

array([ 2,  6, 12, 20, 30])